### ISSUE TITLE
跑不起来

### ISSUE THREAD

**Issue by x363090973** [wmylxmj/Web-Spider-login-bilibili-python3#1]
V16版本 在登录过程中 输完账号密码 弹出图片之后就不再继续了

**Comment by wmylxmj** [comment]
目前最新只有v14版本哦。
有没有报什么错误信息呢?

**Comment by wmylxmj** [comment]
可以试一下最新v14版本的程序

**Comment by wmylxmj** [comment]
如果是打印出已经登录成功的话，可以检查一下安装的chrome与chromedriver是否版本对应

**Comment by wmylxmj** [comment]
如果程序抓到了滑块，并且移动了的话，但是浏览器没反应，那问题可能是版本不对应导致的

**Comment by x363090973** [comment]
感谢回复，我这边 输出 【ok】 inoput password finsshed之后就 没有后续的log输出了，可能真的是版本问题，之前我安装chromedriver  2.41的时候chrome  还是69  现在我发现我的 chrome是70版本的..

**Comment by x363090973** [comment]
我更新了版本还是不行，通过调试发现 gapbp_image = plt.imread(gapbg_filename)
            plt.imshow(gapbp_image)
            plt.show()                   运行第一个plt.show() 时疑似堵塞，此处弹出一张图片之后，单步执行一直在等待中

**Comment by x363090973** [comment]
不好意思给你添麻烦了，我初学python ，这边经过demo测试发现 plt.show()  之后需要手动关闭弹出的图片程序才会继续运行,然后重新运行大侠你的代码  通过手动关闭plt.show() 弹出的图片之后程序可以往下继续运行  我现在去调研这个plt.show()的特性以及  python 代码关闭改图片的方法

**Comment by wmylxmj** [comment]
plt.show()是一个阻塞函数，由于我用的是Ipython Console(交互式)环境，因此没有这个问题，如果你用的是普通的Python脚本，可以用plt.ion()来打开交互模式，只不过这样显示的图片就会一闪而过，看不到打印的图片了。

**Comment by x363090973** [comment]
嗯 我的问题解决了

**Comment by wmylxmj** [comment]
好的
